# Generated by Django 4.2.11 on 2026-04-15 13:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Attention"),
                            ("critical", "Critique"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("message", models.TextField()),
                (
                    "affected_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="analysis.analysisrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-severity", "category"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("time", "Analyse temporelle"),
                            ("performance", "Performance utilisateurs"),
                            ("anomaly", "Détection d'anomalies"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="analysis.analysisrun",
                    ),
                ),
            ],
            options={
                "unique_together": {("run", "result_type")},
            },
        ),
    ]
